//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string clear_passwd { get; set; }
        public string passwd { get; set; }
    }
}
